[package]
name = "gstreamer-recorder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
serde = "1.0.162"
serde_json = "1.0.96"
tokio-tungstenite = "0.18.0"
url = "2.3.1"
